stages:
  train_simple:
    deps:
      - src/train.py
      - data/fashion-mnist/fashion-mnist_train.csv
      - data/fashion-mnist/fashion-mnist_test.csv
    cmd: python src/train.py
    outs:
      - models/fashion_classifier.keras
      
  train_cnn:
    deps:
      - src/train_cnn.py
      - data/fashion-mnist/fashion-mnist_train.csv
    cmd: python src/train_cnn.py
    outs:
      - models/cnn_model.keras

  train_transfer:
    deps:
      - src/train_transfer.py
      - data/fashion-mnist/fashion-mnist_train.csv
    cmd: python src/train_transfer.py
    outs:
      - models/transfer_model.keras

  evaluate:
    deps:
      - src/evaluate.py
      # Dépendances sur les 3 modèles pour la comparaison
      - models/fashion_classifier.keras 
      - models/cnn_model.keras
      - models/transfer_model.keras
      - data/fashion-mnist/fashion-mnist_test.csv
      
    cmd: python src/evaluate.py
    
    metrics:
      - metrics/metrics.json:
          cache: False # Stocké dans Git
          
    plots:
      - metrics/plots/confusion_matrix_simple_mlp.png:
          cache: False
          template: confusion
      - metrics/plots/confusion_matrix_cnn.png:
          cache: False
          template: confusion
      - metrics/plots/confusion_matrix_transfer_learning.png:
          cache: False
          template: confusion