stages:
  train:
    # Dépendances du stage : si le script ou les données changent, ce stage est relancé
    deps:
      - src/train.py
      - data/fashion-mnist/fashion-mnist_train.csv
      - data/fashion-mnist/fashion-mnist_test.csv
      
    # La commande à exécuter (qui va lire les données et sauvegarder le modèle)
    cmd: python src/train.py
    
    # Les sorties : le modèle entraîné (sera versionné par DVC)
    outs:
      - models/fashion_classifier.keras